
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[223] =
    {   0,
       51,   51,   94,   92,   89,   90,   91,   75,   92,   78,
       92,   92,   83,   84,   63,   61,   88,   51,   52,   64,
       51,   92,   87,   69,   65,   70,   48,   92,   60,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   85,   76,   86,   68,   50,    0,
       73,    0,    5,    0,   55,   58,   56,   52,   51,   41,
       52,   59,   52,   51,   80,   32,   77,   71,   67,   66,
       72,   48,   79,   48,   48,   48,   48,   48,   25,   48,
       48,   48,   48,   48,   48,   48,   48,   20,   29,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,

       48,   48,   48,   48,   48,   48,   74,   49,    0,    0,
        0,    0,   52,   52,    9,   48,   48,   48,   48,   48,
       48,   34,   11,   48,   48,   24,   39,   48,    1,   48,
       28,   48,   12,   15,   18,   19,   48,   48,    8,   48,
       48,   31,   48,   48,   48,   48,   37,   48,   48,   48,
        0,    0,   53,   48,    4,    3,   36,   26,   21,   48,
       48,   48,   35,   14,   17,   48,   16,   48,   48,   48,
       48,   48,   10,   22,   47,    7,   48,   38,   53,   54,
       33,    2,   48,   13,   30,   48,   48,   48,   48,   23,
       48,    6,    0,   48,   27,   48,    0,    0,    0,    0,

       48,   40,    0,    0,    0,    0,   48,    0,    0,   45,
        0,    0,   42,    0,    0,   46,    0,    0,    0,   43,
       44,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,    1,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   26,   26,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   26,   50,   51,
       52,   26,   53,   54,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    2,    3,    2,    1,    4,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    5,    5,    5,
        1,    1,    1,    1,    1,    5,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1
    } ;

static const flex_int16_t yy_base[228] =
    {   0,
        0,    0,  322,  323,  323,  323,  323,  297,  314,  323,
      311,    0,   45,  323,   46,  302,  323,   45,   48,  301,
       53,   53,  294,   35,  291,  290,    0,  285,  323,  280,
       40,  273,   41,   38,   48,  276,   45,   51,   61,  263,
      273,  262,   61,   57,  323,  252,  323,  323,  323,  299,
      323,  295,  323,  113,  323,  323,  323,   90,  153,  323,
      156,  323,  159,  164,  323,  323,  323,  323,  323,  323,
      323,    0,  323,  256,  265,  258,  269,  266,  256,  250,
      262,  251,  254,  250,  246,  249,    0,    0,   52,  248,
      241,  245,   66,   65,  244,  238,  251,  245,  150,  237,

      247,    0,  136,  237,  241,  231,  323,  323,  266,    0,
      265,  178,  173,  176,    0,  237,  235,  228,  227,  237,
      236,    0,    0,  223,  238,    0,  235,  221,    0,  232,
        0,  217,  245,    0,    0,    0,  217,  229,  212,  218,
      225,    0,  209,  209,  214,  220,    0,  219,  213,  214,
      188,  240,  238,  207,    0,    0,    0,    0,    0,  213,
      199,  198,    0,    0,    0,  227,    0,  206,  203,  194,
      201,  194,    0,    0,    0,    0,  204,    0,  226,  323,
        0,    0,  198,    0,    0,  201,  205,  195,  191,    0,
      189,    0,  168,  189,    0,  188,  191,  186,  185,  177,

      185,    0,  183,  179,  164,  165,  200,  163,  168,  323,
      167,  194,  323,  165,  160,  323,  155,  150,  135,  323,
      323,  323,  212,  101,   85,  217,  221
    } ;

static const flex_int16_t yy_def[228] =
    {   0,
      222,    1,  222,  222,  222,  222,  222,  222,  223,  222,
      222,  224,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  225,  222,  222,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  222,  222,  222,  222,  222,  223,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  225,  222,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,

      225,  225,  225,  225,  225,  225,  222,  222,  226,   54,
      227,  226,  222,  222,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      226,  222,  226,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  226,  222,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  222,  225,  225,  225,  222,  222,  222,  222,

      225,  225,  222,  222,  222,  222,  225,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,    0,  222,  222,  222,  222,  222
    } ;

static const flex_int16_t yy_nxt[379] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   28,    4,   29,    4,
       30,   31,   32,   33,   34,   35,   27,   36,   37,   38,
       39,   27,   27,   40,   27,   41,   42,   43,   27,   44,
       27,   27,   45,   46,   47,   53,   54,   55,   68,   69,
       58,   56,   59,   59,   59,   61,   61,   61,   63,   60,
       64,   64,   64,   65,   75,   78,   66,   80,   83,   81,
       88,   90,   76,   79,  128,   91,   89,   84,   82,   72,
       85,   96,   92,   93,  105,  106,   86,   94,  101,  129,

      102,   95,  133,   97,  135,   52,  103,  113,  113,  113,
      136,  134,  104,  109,  110,  111,  110,  109,  109,  109,
      109,  109,  109,  109,  112,  109,  109,  109,  109,  109,
      110,  110,  110,  109,  109,  109,  109,  109,  110,  109,
      109,  109,  109,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  109,  109,  109,  114,  221,
       59,   59,   59,   61,   61,   61,   61,   61,   61,   63,
      141,   64,   64,   64,  146,  142,  220,  147,  153,  151,
      113,  113,  113,  113,  113,  113,  219,  143,  179,  151,

      197,  218,  198,  217,  216,  215,  199,  214,  213,  212,
      211,  210,  209,  208,  200,   50,   50,  109,  109,  207,
      109,  109,  111,  111,  206,  111,  205,  204,  203,  202,
      201,  196,  195,  194,  193,  192,  191,  151,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  175,  181,  151,
      180,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  152,  151,  150,  149,
      148,  145,  144,  140,  139,  138,  137,  132,  131,  130,
      127,  126,  125,  124,  123,  122,  121,  120,  119,  118,

      117,  116,  115,  108,   49,  107,  100,   99,   98,   87,
       77,   74,   73,   71,   70,   67,   62,   57,   51,   49,
       48,  222,    3,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222
    } ;

static const flex_int16_t yy_chk[379] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   13,   13,   15,   24,   24,
       18,   15,   18,   18,   18,   19,   19,   19,   21,   18,
       21,   21,   21,   22,   31,   33,   22,   34,   35,   34,
       37,   38,   31,   33,   89,   38,   37,   35,   34,  225,
       35,   39,   38,   38,   44,   44,   35,   38,   43,   89,

       43,   38,   93,   39,   94,  224,   43,   58,   58,   58,
       94,   93,   43,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   59,  219,
       59,   59,   59,   61,   61,   61,   63,   63,   63,   64,
       99,   64,   64,   64,  103,   99,  218,  103,  112,  112,
      113,  113,  113,  114,  114,  114,  217,   99,  151,  151,

      193,  215,  193,  214,  212,  211,  193,  209,  208,  207,
      206,  205,  204,  203,  193,  223,  223,  226,  226,  201,
      226,  226,  227,  227,  200,  227,  199,  198,  197,  196,
      194,  191,  189,  188,  187,  186,  183,  179,  177,  172,
      171,  170,  169,  168,  166,  162,  161,  160,  154,  153,
      152,  150,  149,  148,  146,  145,  144,  143,  141,  140,
      139,  138,  137,  133,  132,  130,  128,  127,  125,  124,
      121,  120,  119,  118,  117,  116,  111,  109,  106,  105,
      104,  101,  100,   98,   97,   96,   95,   92,   91,   90,
       86,   85,   84,   83,   82,   81,   80,   79,   78,   77,

       76,   75,   74,   52,   50,   46,   42,   41,   40,   36,
       32,   30,   28,   26,   25,   23,   20,   16,   11,    9,
        8,    3,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Assignment_ILP_1.l"
#line 2 "Assignment_ILP_1.l"
#include <stdio.h>
#line 600 "lex.yy.c"
#line 601 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 5 "Assignment_ILP_1.l"



#line 822 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 223 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 323 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 8 "Assignment_ILP_1.l"
{printf("T_DATA_TYPE: %s\n",yytext);} //token of data type int
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 9 "Assignment_ILP_1.l"
{printf("T_DATA_TYPE: %s\n",yytext);} //token of data type float
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 10 "Assignment_ILP_1.l"
{printf("T_DATA_TYPE: %s\n",yytext);} //token of data type char 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 11 "Assignment_ILP_1.l"
{printf("T_DATA_TYPE: %s\n",yytext);} //token of data type bool
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 12 "Assignment_ILP_1.l"
{printf("T_DATA_TYPE: %s\n",yytext);} //token of data type unit 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 13 "Assignment_ILP_1.l"
{printf("T_DATA_TYPE: %s\n",yytext);} //token of data type module 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 14 "Assignment_ILP_1.l"
{printf("T_DATA_TYPE: %s\n",yytext);} //token of data type -> type 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 17 "Assignment_ILP_1.l"
{printf("T_OPERATOR: modulus\n");} //modulus operator to find remainder
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 18 "Assignment_ILP_1.l"
{printf("T_OPERATOR: absolute\n");} // absolute operator 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 19 "Assignment_ILP_1.l"
{printf("T_OPERATOR: square root\n");} // square root operator
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 20 "Assignment_ILP_1.l"
{printf("T_OPERATOR: exponential\n");} // power operator
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 21 "Assignment_ILP_1.l"
{printf("T_OPERATOR: logrithmic\n");} // logrithmic operator
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 22 "Assignment_ILP_1.l"
{printf("T_OPERATOR: log base 10 \n");} // logrithm with base 10 operator
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 23 "Assignment_ILP_1.l"
{printf("T_OPERATOR: bitwise and\n");} //bitwise and operator
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 24 "Assignment_ILP_1.l"
{printf("T_OPERATOR: bitwise or\n");} // bitwise or operator 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 25 "Assignment_ILP_1.l"
{printf("T_OPERATOR: bitwise xor\n");} // bitwise xor operator
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 26 "Assignment_ILP_1.l"
{printf("T_OPERATOR: bitwise not\n");} // bitwise not operator
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 27 "Assignment_ILP_1.l"
{printf("T_OPERATOR: bitwise left shift\n");} // left shift operator
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 28 "Assignment_ILP_1.l"
{printf("T_OPERATOR: bitwise right shift\n");} //right shift operator
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 31 "Assignment_ILP_1.l"
{printf("T_IF\n");} //token for if 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 32 "Assignment_ILP_1.l"
{printf("T_ELSE\n");} //token for else 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 33 "Assignment_ILP_1.l"
{printf("T_THEN\n");} // token for then , start of execution if the condition of if is true
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 34 "Assignment_ILP_1.l"
{printf("T_WHILE\n");} // token for while 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 35 "Assignment_ILP_1.l"
{printf("T_FOR\n");} // token for -> for 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 36 "Assignment_ILP_1.l"
{printf("T_DO\n");} // token for do , starts the loop if loop condition is true
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 37 "Assignment_ILP_1.l"
{printf("T_DONE\n");}  // token for done , it helps in termination of loops 
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "Assignment_ILP_1.l"
{printf("T_RETURN_STATEMENT\n");} //for returning from the function 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "Assignment_ILP_1.l"
{printf("T_CORE_LANGUAGE_KEYWORD_LET\n");} // decleration of a variable 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 42 "Assignment_ILP_1.l"
{printf("T_CORE_LANGUAGE_KEYWORD_IN\n");} // pushing a value from one statement to next 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 43 "Assignment_ILP_1.l"
{printf("T_KEYWORD_TO_MATCH_SYNTAX\n");} // macthing the pattern 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 46 "Assignment_ILP_1.l"
{printf("T_REFERENCE_OPERATOR\n");} //this is a keyword that is used to declare mutable data-types in functional programming
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 47 "Assignment_ILP_1.l"
{printf("T_ASSIGNMENT_OPERATOR\n");} // assigning the value or we can by this we can change the value of the referenced variable 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 48 "Assignment_ILP_1.l"
{printf("T_BEGINNING_OF_REFERENCING\n");} //if we want to code some lines of code using referncing in ocamel we start that part of code by begin  
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 49 "Assignment_ILP_1.l"
{printf("T_ENDING_OF_REFERENCING\n");} // if we are coding some lines of code by using referencing in ocamel then we finish that part of code by end
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 50 "Assignment_ILP_1.l"
{printf("T_INCREMENT_OPERATOR\n");} // increasing the value of the variable/integer by 1
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 51 "Assignment_ILP_1.l"
{printf("T_DECREMENT_OPERATOR\n");} // decreasing the value of the variable/integer by 1
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 54 "Assignment_ILP_1.l"
{printf("T_TRY_FOR_EXECPTION_HANDLING\n");} // in exception handling in ocamel we start by the statement of try in which we do the required operations 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 55 "Assignment_ILP_1.l"
{printf("T_WITH_FOR_EXECPTION_HANDLING\n");} // in with there is a set of rules written about the exceptions that might occur 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 58 "Assignment_ILP_1.l"
{printf("T_DECLERATION_OF_ANONYMOUS_FUNCTION\n");} //decleration of user defined function 
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 59 "Assignment_ILP_1.l"
{printf("T_DECLERATION_OF_PATTERN_MATCHING_FUNCTION\n");} //decleration of function that are used for pattern matching 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 60 "Assignment_ILP_1.l"
{printf("T_FUNCTION_ASSIGNING\n");} // defnining the rules from variable to variable 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "Assignment_ILP_1.l"
{printf("T_PRINT_CHAR\n");} // printing a character value
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "Assignment_ILP_1.l"
{printf("T_PIRNT_STRING\n");} //printing a string value
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 65 "Assignment_ILP_1.l"
{printf("T_PRINT_ENDLINE\n");} // simply equal to \n
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "Assignment_ILP_1.l"
{printf("T_PRINT_INTEGER\n");} //printing an integer value
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "Assignment_ILP_1.l"
{printf("T_READ\n");} //reading or taking input from user
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 72 "Assignment_ILP_1.l"
{printf("T_BOOLEAN_LITERAL: %s\n",yytext);} //literal of boolean type
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 73 "Assignment_ILP_1.l"
{printf("T_IDENTIFIER_LITERAL: %s\n", yytext);} //regex to match identifier
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 74 "Assignment_ILP_1.l"
{printf("T_CHARACTER_LITERAL: %s\n", yytext);} // regex to match character
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 75 "Assignment_ILP_1.l"
{printf("T_STRING_LITERAL: %s\n", yytext);} // regex to match string
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 76 "Assignment_ILP_1.l"
{printf("T_NUMBER_LITERAL: %s\n",yytext);} // regex to match integer 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 77 "Assignment_ILP_1.l"
{printf("T_FLOAT_LITERAL: %s\n",yytext);} // regex to match float 
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 79 "Assignment_ILP_1.l"
{printf("T_COMMENT\n");}  // regex to match single line comment
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 80 "Assignment_ILP_1.l"
{printf("T_MULTI_LINE_COMMENT");} // regex to match multi-line-comment 
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "Assignment_ILP_1.l"
{printf("T_OPERATOR: **(exponential/power)\n");} // exponential operator
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 83 "Assignment_ILP_1.l"
{printf("T_OPERATOR: +.(addition of float types variables/constants )\n");} // addition of 2 float values
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 84 "Assignment_ILP_1.l"
{printf("T_OPERATOR: -.(subtraction of float type variables/constants)\n");} // subtraction of 2 float values
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 "Assignment_ILP_1.l"
{printf("T_OPERATOR: *.(multiplication of float variables/constants)\n");} // multiplication of 2 float values
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 86 "Assignment_ILP_1.l"
{printf("T_OPERATOR: /.(division of float variables/constants)\n");} // division of 2 float values 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 87 "Assignment_ILP_1.l"
{printf("T_OPERATOR: ^(string concatenation)");} // concatenating 2 strings
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 88 "Assignment_ILP_1.l"
{printf("T_OPERATOR: +(addition)\n");} // addition operator 
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 "Assignment_ILP_1.l"
{printf("T_OPERATOR: -(subtraction)\n");} // subtraction operator 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "Assignment_ILP_1.l"
{printf("T_OPERATOR: *(multiplication)\n");} //multiplication operator
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 "Assignment_ILP_1.l"
{printf("T_OPERATOR: /(division)\n");} //division operator
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 92 "Assignment_ILP_1.l"
{printf("T_OPERATOR: =(structural equality)\n");} //check if the value of both operands are same or not
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 93 "Assignment_ILP_1.l"
{printf("T_OPERATOR: ==(physical equality)\n");} //also check if the data-types are same or not.
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 94 "Assignment_ILP_1.l"
{printf("T_OPERATOR: <>(structural not equal");} //	check if the values are not same 	
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 95 "Assignment_ILP_1.l"
{printf("T_OPERATOR: !=(physical not equal to)\n");} //also checks if data- types are also not the same
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 96 "Assignment_ILP_1.l"
{printf("T_OPERATOR: <(more than)\n");} //more than operator
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 97 "Assignment_ILP_1.l"
{printf("T_OPERATOR: >(less than)\n");} //less tahn operator 
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 98 "Assignment_ILP_1.l"
{printf("T_OPERATOR: <=(more than equal to)\n");} //more than or equal to opertor 
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 99 "Assignment_ILP_1.l"
{printf("T_OPERATOR: >=(less tahn equal to)\n");} //less than or equal to operator 
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 100 "Assignment_ILP_1.l"
{printf("T_OPERATOR: &&(logical and)\n");} // logical and 
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 101 "Assignment_ILP_1.l"
{printf("T_OPERATOR: ||(logical or)\n");} // logical or
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 102 "Assignment_ILP_1.l"
{printf("T_OPERATOR: !(logical not)  or   derefernce operator depends on the syntax\n");} //logical not
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 103 "Assignment_ILP_1.l"
{printf("T_SEPERATION_IN_PATTERN_MACTHING");} //or for pattern matching 
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 104 "Assignment_ILP_1.l"
{printf("T_END_OF_LINE");} //another way of representing /n
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 105 "Assignment_ILP_1.l"
{printf("T_HASH");} //token for hash occurs in start of line in OCamel
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 107 "Assignment_ILP_1.l"
{printf("T_EMPTY_LIST\n");} //creates an empty list
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 108 "Assignment_ILP_1.l"
{printf("T_OPERATOR_TO_SEPERATE_LIST_ITEMS\n");} // seperates the elements in the list 
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 109 "Assignment_ILP_1.l"
{printf("T_LIST_OPERATION_RETURNS_HEAD_OF_LIST\n");} //returns first element of the list 
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 110 "Assignment_ILP_1.l"
{printf("T_LIST_OPERATION_RETURNS_TAIL_OF_LIST\n");} //returns last element of the list
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 112 "Assignment_ILP_1.l"
{printf("T_LEFT_PARENTHESIS\n");} //left parenthesis
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 113 "Assignment_ILP_1.l"
{printf("T_RIGHT_PARENTHESIS\n");} //right parenthesis
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 114 "Assignment_ILP_1.l"
{printf("T_LEFT_BRACKETS\n");} //;eft curly brackets
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 115 "Assignment_ILP_1.l"
{printf("T_RIGHT_BRACKETS\n");} //right curly brackets
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 116 "Assignment_ILP_1.l"
{printf("T_SEMICOLON\n");} //semi-colon
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 117 "Assignment_ILP_1.l"
{printf("T_COMMA\n");} //comma
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 118 "Assignment_ILP_1.l"
{printf("T_TAB_SPACE\n"); } //tab space
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 119 "Assignment_ILP_1.l"
{printf("T_NEW_LINE_CHARACTER\n");} //new line character
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 121 "Assignment_ILP_1.l"
{printf(" ");} //space , no token for space 
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 123 "Assignment_ILP_1.l"
{printf("UNKNOWN_TOKEN: %s\n", yytext);} //for all others 
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 125 "Assignment_ILP_1.l"
ECHO;
	YY_BREAK
#line 1346 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 223 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 223 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 222);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 125 "Assignment_ILP_1.l"



int yywrap(){
	return 1;
}


int main() {
    printf("enter string: ");
    yylex();
    return 0;
}


